// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer_service.proto

package clients;

public final class AnswerServiceProtos {
  private AnswerServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnswerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.AnswerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    boolean hasJsonQuestionDataset();
    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    java.lang.String getJsonQuestionDataset();
    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonQuestionDatasetBytes();
  }
  /**
   * Protobuf type {@code services.AnswerRequest}
   */
  public  static final class AnswerRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.AnswerRequest)
      AnswerRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnswerRequest.newBuilder() to construct.
    private AnswerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnswerRequest() {
      jsonQuestionDataset_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnswerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              jsonQuestionDataset_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clients.AnswerServiceProtos.internal_static_services_AnswerRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clients.AnswerServiceProtos.internal_static_services_AnswerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clients.AnswerServiceProtos.AnswerRequest.class, clients.AnswerServiceProtos.AnswerRequest.Builder.class);
    }

    private int bitField0_;
    public static final int JSON_QUESTION_DATASET_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonQuestionDataset_;
    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    public boolean hasJsonQuestionDataset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    public java.lang.String getJsonQuestionDataset() {
      java.lang.Object ref = jsonQuestionDataset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonQuestionDataset_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A QuestionDataSet which is JSONed.
     * </pre>
     *
     * <code>required string json_question_dataset = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonQuestionDatasetBytes() {
      java.lang.Object ref = jsonQuestionDataset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonQuestionDataset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasJsonQuestionDataset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonQuestionDataset_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonQuestionDataset_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clients.AnswerServiceProtos.AnswerRequest)) {
        return super.equals(obj);
      }
      clients.AnswerServiceProtos.AnswerRequest other = (clients.AnswerServiceProtos.AnswerRequest) obj;

      boolean result = true;
      result = result && (hasJsonQuestionDataset() == other.hasJsonQuestionDataset());
      if (hasJsonQuestionDataset()) {
        result = result && getJsonQuestionDataset()
            .equals(other.getJsonQuestionDataset());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasJsonQuestionDataset()) {
        hash = (37 * hash) + JSON_QUESTION_DATASET_FIELD_NUMBER;
        hash = (53 * hash) + getJsonQuestionDataset().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clients.AnswerServiceProtos.AnswerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.AnswerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.AnswerRequest)
        clients.AnswerServiceProtos.AnswerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clients.AnswerServiceProtos.AnswerRequest.class, clients.AnswerServiceProtos.AnswerRequest.Builder.class);
      }

      // Construct using clients.AnswerServiceProtos.AnswerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        jsonQuestionDataset_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerRequest_descriptor;
      }

      public clients.AnswerServiceProtos.AnswerRequest getDefaultInstanceForType() {
        return clients.AnswerServiceProtos.AnswerRequest.getDefaultInstance();
      }

      public clients.AnswerServiceProtos.AnswerRequest build() {
        clients.AnswerServiceProtos.AnswerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clients.AnswerServiceProtos.AnswerRequest buildPartial() {
        clients.AnswerServiceProtos.AnswerRequest result = new clients.AnswerServiceProtos.AnswerRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jsonQuestionDataset_ = jsonQuestionDataset_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clients.AnswerServiceProtos.AnswerRequest) {
          return mergeFrom((clients.AnswerServiceProtos.AnswerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clients.AnswerServiceProtos.AnswerRequest other) {
        if (other == clients.AnswerServiceProtos.AnswerRequest.getDefaultInstance()) return this;
        if (other.hasJsonQuestionDataset()) {
          bitField0_ |= 0x00000001;
          jsonQuestionDataset_ = other.jsonQuestionDataset_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJsonQuestionDataset()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clients.AnswerServiceProtos.AnswerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clients.AnswerServiceProtos.AnswerRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object jsonQuestionDataset_ = "";
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public boolean hasJsonQuestionDataset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public java.lang.String getJsonQuestionDataset() {
        java.lang.Object ref = jsonQuestionDataset_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonQuestionDataset_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonQuestionDatasetBytes() {
        java.lang.Object ref = jsonQuestionDataset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonQuestionDataset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public Builder setJsonQuestionDataset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonQuestionDataset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public Builder clearJsonQuestionDataset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonQuestionDataset_ = getDefaultInstance().getJsonQuestionDataset();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A QuestionDataSet which is JSONed.
       * </pre>
       *
       * <code>required string json_question_dataset = 1;</code>
       */
      public Builder setJsonQuestionDatasetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonQuestionDataset_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:services.AnswerRequest)
    }

    // @@protoc_insertion_point(class_scope:services.AnswerRequest)
    private static final clients.AnswerServiceProtos.AnswerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clients.AnswerServiceProtos.AnswerRequest();
    }

    public static clients.AnswerServiceProtos.AnswerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AnswerRequest>
        PARSER = new com.google.protobuf.AbstractParser<AnswerRequest>() {
      public AnswerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnswerRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnswerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnswerRequest> getParserForType() {
      return PARSER;
    }

    public clients.AnswerServiceProtos.AnswerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnswerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.AnswerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    java.util.List<java.lang.Double> getScoresList();
    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    int getScoresCount();
    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    double getScores(int index);

    /**
     * <code>required string exit_code = 2;</code>
     */
    boolean hasExitCode();
    /**
     * <code>required string exit_code = 2;</code>
     */
    java.lang.String getExitCode();
    /**
     * <code>required string exit_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getExitCodeBytes();
  }
  /**
   * Protobuf type {@code services.AnswerResponse}
   */
  public  static final class AnswerResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.AnswerResponse)
      AnswerResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnswerResponse.newBuilder() to construct.
    private AnswerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnswerResponse() {
      scores_ = java.util.Collections.emptyList();
      exitCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnswerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                scores_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              scores_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                scores_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                scores_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              exitCode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clients.AnswerServiceProtos.internal_static_services_AnswerResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clients.AnswerServiceProtos.internal_static_services_AnswerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              clients.AnswerServiceProtos.AnswerResponse.class, clients.AnswerServiceProtos.AnswerResponse.Builder.class);
    }

    private int bitField0_;
    public static final int SCORES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> scores_;
    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getScoresList() {
      return scores_;
    }
    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <pre>
     * 4 * num_entries.
     * </pre>
     *
     * <code>repeated double scores = 1;</code>
     */
    public double getScores(int index) {
      return scores_.get(index);
    }

    public static final int EXIT_CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object exitCode_;
    /**
     * <code>required string exit_code = 2;</code>
     */
    public boolean hasExitCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string exit_code = 2;</code>
     */
    public java.lang.String getExitCode() {
      java.lang.Object ref = exitCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exitCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string exit_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExitCodeBytes() {
      java.lang.Object ref = exitCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exitCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasExitCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < scores_.size(); i++) {
        output.writeDouble(1, scores_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exitCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getScoresList().size();
        size += dataSize;
        size += 1 * getScoresList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exitCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof clients.AnswerServiceProtos.AnswerResponse)) {
        return super.equals(obj);
      }
      clients.AnswerServiceProtos.AnswerResponse other = (clients.AnswerServiceProtos.AnswerResponse) obj;

      boolean result = true;
      result = result && getScoresList()
          .equals(other.getScoresList());
      result = result && (hasExitCode() == other.hasExitCode());
      if (hasExitCode()) {
        result = result && getExitCode()
            .equals(other.getExitCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getScoresCount() > 0) {
        hash = (37 * hash) + SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getScoresList().hashCode();
      }
      if (hasExitCode()) {
        hash = (37 * hash) + EXIT_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getExitCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static clients.AnswerServiceProtos.AnswerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(clients.AnswerServiceProtos.AnswerResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.AnswerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.AnswerResponse)
        clients.AnswerServiceProtos.AnswerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                clients.AnswerServiceProtos.AnswerResponse.class, clients.AnswerServiceProtos.AnswerResponse.Builder.class);
      }

      // Construct using clients.AnswerServiceProtos.AnswerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        exitCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clients.AnswerServiceProtos.internal_static_services_AnswerResponse_descriptor;
      }

      public clients.AnswerServiceProtos.AnswerResponse getDefaultInstanceForType() {
        return clients.AnswerServiceProtos.AnswerResponse.getDefaultInstance();
      }

      public clients.AnswerServiceProtos.AnswerResponse build() {
        clients.AnswerServiceProtos.AnswerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public clients.AnswerServiceProtos.AnswerResponse buildPartial() {
        clients.AnswerServiceProtos.AnswerResponse result = new clients.AnswerServiceProtos.AnswerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scores_ = scores_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exitCode_ = exitCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clients.AnswerServiceProtos.AnswerResponse) {
          return mergeFrom((clients.AnswerServiceProtos.AnswerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(clients.AnswerServiceProtos.AnswerResponse other) {
        if (other == clients.AnswerServiceProtos.AnswerResponse.getDefaultInstance()) return this;
        if (!other.scores_.isEmpty()) {
          if (scores_.isEmpty()) {
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScoresIsMutable();
            scores_.addAll(other.scores_);
          }
          onChanged();
        }
        if (other.hasExitCode()) {
          bitField0_ |= 0x00000002;
          exitCode_ = other.exitCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExitCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        clients.AnswerServiceProtos.AnswerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (clients.AnswerServiceProtos.AnswerResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Double> scores_ = java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = new java.util.ArrayList<java.lang.Double>(scores_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public java.util.List<java.lang.Double>
          getScoresList() {
        return java.util.Collections.unmodifiableList(scores_);
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public int getScoresCount() {
        return scores_.size();
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public double getScores(int index) {
        return scores_.get(index);
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public Builder setScores(
          int index, double value) {
        ensureScoresIsMutable();
        scores_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public Builder addScores(double value) {
        ensureScoresIsMutable();
        scores_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public Builder addAllScores(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureScoresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scores_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 4 * num_entries.
       * </pre>
       *
       * <code>repeated double scores = 1;</code>
       */
      public Builder clearScores() {
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.lang.Object exitCode_ = "";
      /**
       * <code>required string exit_code = 2;</code>
       */
      public boolean hasExitCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string exit_code = 2;</code>
       */
      public java.lang.String getExitCode() {
        java.lang.Object ref = exitCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exitCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string exit_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getExitCodeBytes() {
        java.lang.Object ref = exitCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exitCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string exit_code = 2;</code>
       */
      public Builder setExitCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exitCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string exit_code = 2;</code>
       */
      public Builder clearExitCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exitCode_ = getDefaultInstance().getExitCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string exit_code = 2;</code>
       */
      public Builder setExitCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exitCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:services.AnswerResponse)
    }

    // @@protoc_insertion_point(class_scope:services.AnswerResponse)
    private static final clients.AnswerServiceProtos.AnswerResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new clients.AnswerServiceProtos.AnswerResponse();
    }

    public static clients.AnswerServiceProtos.AnswerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AnswerResponse>
        PARSER = new com.google.protobuf.AbstractParser<AnswerResponse>() {
      public AnswerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnswerResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnswerResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnswerResponse> getParserForType() {
      return PARSER;
    }

    public clients.AnswerServiceProtos.AnswerResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_AnswerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_AnswerRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_AnswerResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_AnswerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024answer_service.proto\022\010services\".\n\rAnsw" +
      "erRequest\022\035\n\025json_question_dataset\030\001 \002(\t" +
      "\"3\n\016AnswerResponse\022\016\n\006scores\030\001 \003(\001\022\021\n\tex" +
      "it_code\030\002 \002(\t2N\n\rAnswerService\022=\n\006Answer" +
      "\022\027.services.AnswerRequest\032\030.services.Ans" +
      "werResponse\"\000B\036\n\007clientsB\023AnswerServiceP" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_services_AnswerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_AnswerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_AnswerRequest_descriptor,
        new java.lang.String[] { "JsonQuestionDataset", });
    internal_static_services_AnswerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_AnswerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_AnswerResponse_descriptor,
        new java.lang.String[] { "Scores", "ExitCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
