# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essential_terms_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='essential_terms_service.proto',
  package='services',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x65ssential_terms_service.proto\x12\x08services\"~\n\x0f\x45TScoresRequest\x12\x30\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1f.services.ETScoresRequest.Entry\x1a\x39\n\x05\x45ntry\x12\x10\n\x08question\x18\x01 \x02(\t\x12\x0f\n\x07\x61nswers\x18\x02 \x03(\t\x12\r\n\x05terms\x18\x03 \x03(\t\"\xf2\x01\n\x10\x45TScoresResponse\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .services.ETScoresResponse.Entry\x12\x11\n\texit_code\x18\x02 \x02(\t\x1a\x97\x01\n\x05\x45ntry\x12\x10\n\x08question\x18\x01 \x02(\t\x12\x0f\n\x07\x61nswers\x18\x02 \x03(\t\x12<\n\x06scores\x18\x03 \x03(\x0b\x32,.services.ETScoresResponse.Entry.ScoresEntry\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"*\n\x1a\x45TScoresCompressedResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x32\xcd\x01\n\tETService\x12]\n\x16GetEssentialnessScores\x12\x19.services.ETScoresRequest\x1a$.services.ETScoresCompressedResponse\"\x00\x30\x01\x12\x61\n\x1aGetEssentialnessScoresFake\x12\x19.services.ETScoresRequest\x1a$.services.ETScoresCompressedResponse\"\x00\x30\x01\x42\x1a\n\x07\x63lientsB\x0f\x45TServiceProtos')
)




_ETSCORESREQUEST_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='services.ETScoresRequest.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='services.ETScoresRequest.Entry.question', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answers', full_name='services.ETScoresRequest.Entry.answers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='terms', full_name='services.ETScoresRequest.Entry.terms', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=169,
)

_ETSCORESREQUEST = _descriptor.Descriptor(
  name='ETScoresRequest',
  full_name='services.ETScoresRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='services.ETScoresRequest.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ETSCORESREQUEST_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=169,
)


_ETSCORESRESPONSE_ENTRY_SCORESENTRY = _descriptor.Descriptor(
  name='ScoresEntry',
  full_name='services.ETScoresResponse.Entry.ScoresEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='services.ETScoresResponse.Entry.ScoresEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='services.ETScoresResponse.Entry.ScoresEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=414,
)

_ETSCORESRESPONSE_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='services.ETScoresResponse.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='services.ETScoresResponse.Entry.question', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answers', full_name='services.ETScoresResponse.Entry.answers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='services.ETScoresResponse.Entry.scores', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ETSCORESRESPONSE_ENTRY_SCORESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=414,
)

_ETSCORESRESPONSE = _descriptor.Descriptor(
  name='ETScoresResponse',
  full_name='services.ETScoresResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='services.ETScoresResponse.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='services.ETScoresResponse.exit_code', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ETSCORESRESPONSE_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=414,
)


_ETSCORESCOMPRESSEDRESPONSE = _descriptor.Descriptor(
  name='ETScoresCompressedResponse',
  full_name='services.ETScoresCompressedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='services.ETScoresCompressedResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=458,
)

_ETSCORESREQUEST_ENTRY.containing_type = _ETSCORESREQUEST
_ETSCORESREQUEST.fields_by_name['entries'].message_type = _ETSCORESREQUEST_ENTRY
_ETSCORESRESPONSE_ENTRY_SCORESENTRY.containing_type = _ETSCORESRESPONSE_ENTRY
_ETSCORESRESPONSE_ENTRY.fields_by_name['scores'].message_type = _ETSCORESRESPONSE_ENTRY_SCORESENTRY
_ETSCORESRESPONSE_ENTRY.containing_type = _ETSCORESRESPONSE
_ETSCORESRESPONSE.fields_by_name['entries'].message_type = _ETSCORESRESPONSE_ENTRY
DESCRIPTOR.message_types_by_name['ETScoresRequest'] = _ETSCORESREQUEST
DESCRIPTOR.message_types_by_name['ETScoresResponse'] = _ETSCORESRESPONSE
DESCRIPTOR.message_types_by_name['ETScoresCompressedResponse'] = _ETSCORESCOMPRESSEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ETScoresRequest = _reflection.GeneratedProtocolMessageType('ETScoresRequest', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _ETSCORESREQUEST_ENTRY,
    __module__ = 'essential_terms_service_pb2'
    # @@protoc_insertion_point(class_scope:services.ETScoresRequest.Entry)
    ))
  ,
  DESCRIPTOR = _ETSCORESREQUEST,
  __module__ = 'essential_terms_service_pb2'
  # @@protoc_insertion_point(class_scope:services.ETScoresRequest)
  ))
_sym_db.RegisterMessage(ETScoresRequest)
_sym_db.RegisterMessage(ETScoresRequest.Entry)

ETScoresResponse = _reflection.GeneratedProtocolMessageType('ETScoresResponse', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(

    ScoresEntry = _reflection.GeneratedProtocolMessageType('ScoresEntry', (_message.Message,), dict(
      DESCRIPTOR = _ETSCORESRESPONSE_ENTRY_SCORESENTRY,
      __module__ = 'essential_terms_service_pb2'
      # @@protoc_insertion_point(class_scope:services.ETScoresResponse.Entry.ScoresEntry)
      ))
    ,
    DESCRIPTOR = _ETSCORESRESPONSE_ENTRY,
    __module__ = 'essential_terms_service_pb2'
    # @@protoc_insertion_point(class_scope:services.ETScoresResponse.Entry)
    ))
  ,
  DESCRIPTOR = _ETSCORESRESPONSE,
  __module__ = 'essential_terms_service_pb2'
  # @@protoc_insertion_point(class_scope:services.ETScoresResponse)
  ))
_sym_db.RegisterMessage(ETScoresResponse)
_sym_db.RegisterMessage(ETScoresResponse.Entry)
_sym_db.RegisterMessage(ETScoresResponse.Entry.ScoresEntry)

ETScoresCompressedResponse = _reflection.GeneratedProtocolMessageType('ETScoresCompressedResponse', (_message.Message,), dict(
  DESCRIPTOR = _ETSCORESCOMPRESSEDRESPONSE,
  __module__ = 'essential_terms_service_pb2'
  # @@protoc_insertion_point(class_scope:services.ETScoresCompressedResponse)
  ))
_sym_db.RegisterMessage(ETScoresCompressedResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007clientsB\017ETServiceProtos'))
_ETSCORESRESPONSE_ENTRY_SCORESENTRY.has_options = True
_ETSCORESRESPONSE_ENTRY_SCORESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_ETSERVICE = _descriptor.ServiceDescriptor(
  name='ETService',
  full_name='services.ETService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=461,
  serialized_end=666,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEssentialnessScores',
    full_name='services.ETService.GetEssentialnessScores',
    index=0,
    containing_service=None,
    input_type=_ETSCORESREQUEST,
    output_type=_ETSCORESCOMPRESSEDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEssentialnessScoresFake',
    full_name='services.ETService.GetEssentialnessScoresFake',
    index=1,
    containing_service=None,
    input_type=_ETSCORESREQUEST,
    output_type=_ETSCORESCOMPRESSEDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ETSERVICE)

DESCRIPTOR.services_by_name['ETService'] = _ETSERVICE

# @@protoc_insertion_point(module_scope)
