// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concretness_ratings.proto

package data;

public final class ConcretenessRatingsProtos {
  private ConcretenessRatingsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.Entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Whether it is a single word or a two-word expression.
     * </pre>
     *
     * <code>required bool bigram = 1;</code>
     */
    boolean hasBigram();
    /**
     * <pre>
     * Whether it is a single word or a two-word expression.
     * </pre>
     *
     * <code>required bool bigram = 1;</code>
     */
    boolean getBigram();

    /**
     * <pre>
     * The mean concreteness rating.
     * </pre>
     *
     * <code>required double rating = 2;</code>
     */
    boolean hasRating();
    /**
     * <pre>
     * The mean concreteness rating.
     * </pre>
     *
     * <code>required double rating = 2;</code>
     */
    double getRating();

    /**
     * <pre>
     * The standard deviation of the concreteness ratings.
     * </pre>
     *
     * <code>required double rating_sd = 3;</code>
     */
    boolean hasRatingSd();
    /**
     * <pre>
     * The standard deviation of the concreteness ratings.
     * </pre>
     *
     * <code>required double rating_sd = 3;</code>
     */
    double getRatingSd();

    /**
     * <pre>
     * The number of persons indicating they did not know the word.
     * </pre>
     *
     * <code>required uint32 unknown = 4;</code>
     */
    boolean hasUnknown();
    /**
     * <pre>
     * The number of persons indicating they did not know the word.
     * </pre>
     *
     * <code>required uint32 unknown = 4;</code>
     */
    int getUnknown();

    /**
     * <pre>
     * The total number of persons who rated the word.
     * </pre>
     *
     * <code>required uint32 num_persons = 5;</code>
     */
    boolean hasNumPersons();
    /**
     * <pre>
     * The total number of persons who rated the word.
     * </pre>
     *
     * <code>required uint32 num_persons = 5;</code>
     */
    int getNumPersons();

    /**
     * <pre>
     * Percentage participants who knew the word.
     * </pre>
     *
     * <code>required double known_percentage = 6;</code>
     */
    boolean hasKnownPercentage();
    /**
     * <pre>
     * Percentage participants who knew the word.
     * </pre>
     *
     * <code>required double known_percentage = 6;</code>
     */
    double getKnownPercentage();

    /**
     * <pre>
     * The SUBTLEX-US frequency count (on a total of 51 million).
     * </pre>
     *
     * <code>required uint64 frequency_count = 7;</code>
     */
    boolean hasFrequencyCount();
    /**
     * <pre>
     * The SUBTLEX-US frequency count (on a total of 51 million).
     * </pre>
     *
     * <code>required uint64 frequency_count = 7;</code>
     */
    long getFrequencyCount();

    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code data.Entry}
   */
  public  static final class Entry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.Entry)
      EntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entry() {
      bigram_ = false;
      rating_ = 0D;
      ratingSd_ = 0D;
      unknown_ = 0;
      numPersons_ = 0;
      knownPercentage_ = 0D;
      frequencyCount_ = 0L;
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bigram_ = input.readBool();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              rating_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              ratingSd_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              unknown_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              numPersons_ = input.readUInt32();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              knownPercentage_ = input.readDouble();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              frequencyCount_ = input.readUInt64();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              type_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.ConcretenessRatingsProtos.internal_static_data_Entry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.ConcretenessRatingsProtos.internal_static_data_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.ConcretenessRatingsProtos.Entry.class, data.ConcretenessRatingsProtos.Entry.Builder.class);
    }

    private int bitField0_;
    public static final int BIGRAM_FIELD_NUMBER = 1;
    private boolean bigram_;
    /**
     * <pre>
     * Whether it is a single word or a two-word expression.
     * </pre>
     *
     * <code>required bool bigram = 1;</code>
     */
    public boolean hasBigram() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Whether it is a single word or a two-word expression.
     * </pre>
     *
     * <code>required bool bigram = 1;</code>
     */
    public boolean getBigram() {
      return bigram_;
    }

    public static final int RATING_FIELD_NUMBER = 2;
    private double rating_;
    /**
     * <pre>
     * The mean concreteness rating.
     * </pre>
     *
     * <code>required double rating = 2;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * The mean concreteness rating.
     * </pre>
     *
     * <code>required double rating = 2;</code>
     */
    public double getRating() {
      return rating_;
    }

    public static final int RATING_SD_FIELD_NUMBER = 3;
    private double ratingSd_;
    /**
     * <pre>
     * The standard deviation of the concreteness ratings.
     * </pre>
     *
     * <code>required double rating_sd = 3;</code>
     */
    public boolean hasRatingSd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * The standard deviation of the concreteness ratings.
     * </pre>
     *
     * <code>required double rating_sd = 3;</code>
     */
    public double getRatingSd() {
      return ratingSd_;
    }

    public static final int UNKNOWN_FIELD_NUMBER = 4;
    private int unknown_;
    /**
     * <pre>
     * The number of persons indicating they did not know the word.
     * </pre>
     *
     * <code>required uint32 unknown = 4;</code>
     */
    public boolean hasUnknown() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * The number of persons indicating they did not know the word.
     * </pre>
     *
     * <code>required uint32 unknown = 4;</code>
     */
    public int getUnknown() {
      return unknown_;
    }

    public static final int NUM_PERSONS_FIELD_NUMBER = 5;
    private int numPersons_;
    /**
     * <pre>
     * The total number of persons who rated the word.
     * </pre>
     *
     * <code>required uint32 num_persons = 5;</code>
     */
    public boolean hasNumPersons() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * The total number of persons who rated the word.
     * </pre>
     *
     * <code>required uint32 num_persons = 5;</code>
     */
    public int getNumPersons() {
      return numPersons_;
    }

    public static final int KNOWN_PERCENTAGE_FIELD_NUMBER = 6;
    private double knownPercentage_;
    /**
     * <pre>
     * Percentage participants who knew the word.
     * </pre>
     *
     * <code>required double known_percentage = 6;</code>
     */
    public boolean hasKnownPercentage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * Percentage participants who knew the word.
     * </pre>
     *
     * <code>required double known_percentage = 6;</code>
     */
    public double getKnownPercentage() {
      return knownPercentage_;
    }

    public static final int FREQUENCY_COUNT_FIELD_NUMBER = 7;
    private long frequencyCount_;
    /**
     * <pre>
     * The SUBTLEX-US frequency count (on a total of 51 million).
     * </pre>
     *
     * <code>required uint64 frequency_count = 7;</code>
     */
    public boolean hasFrequencyCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * The SUBTLEX-US frequency count (on a total of 51 million).
     * </pre>
     *
     * <code>required uint64 frequency_count = 7;</code>
     */
    public long getFrequencyCount() {
      return frequencyCount_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Adjective, Noun, Verb, N/A.
     * </pre>
     *
     * <code>required string type = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBigram()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRating()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRatingSd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUnknown()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumPersons()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKnownPercentage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrequencyCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, bigram_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, rating_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, ratingSd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, unknown_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, numPersons_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, knownPercentage_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, frequencyCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, bigram_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, rating_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, ratingSd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, unknown_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, numPersons_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, knownPercentage_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, frequencyCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.ConcretenessRatingsProtos.Entry)) {
        return super.equals(obj);
      }
      data.ConcretenessRatingsProtos.Entry other = (data.ConcretenessRatingsProtos.Entry) obj;

      boolean result = true;
      result = result && (hasBigram() == other.hasBigram());
      if (hasBigram()) {
        result = result && (getBigram()
            == other.getBigram());
      }
      result = result && (hasRating() == other.hasRating());
      if (hasRating()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getRating())
            == java.lang.Double.doubleToLongBits(
                other.getRating()));
      }
      result = result && (hasRatingSd() == other.hasRatingSd());
      if (hasRatingSd()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getRatingSd())
            == java.lang.Double.doubleToLongBits(
                other.getRatingSd()));
      }
      result = result && (hasUnknown() == other.hasUnknown());
      if (hasUnknown()) {
        result = result && (getUnknown()
            == other.getUnknown());
      }
      result = result && (hasNumPersons() == other.hasNumPersons());
      if (hasNumPersons()) {
        result = result && (getNumPersons()
            == other.getNumPersons());
      }
      result = result && (hasKnownPercentage() == other.hasKnownPercentage());
      if (hasKnownPercentage()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getKnownPercentage())
            == java.lang.Double.doubleToLongBits(
                other.getKnownPercentage()));
      }
      result = result && (hasFrequencyCount() == other.hasFrequencyCount());
      if (hasFrequencyCount()) {
        result = result && (getFrequencyCount()
            == other.getFrequencyCount());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBigram()) {
        hash = (37 * hash) + BIGRAM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBigram());
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getRating()));
      }
      if (hasRatingSd()) {
        hash = (37 * hash) + RATING_SD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getRatingSd()));
      }
      if (hasUnknown()) {
        hash = (37 * hash) + UNKNOWN_FIELD_NUMBER;
        hash = (53 * hash) + getUnknown();
      }
      if (hasNumPersons()) {
        hash = (37 * hash) + NUM_PERSONS_FIELD_NUMBER;
        hash = (53 * hash) + getNumPersons();
      }
      if (hasKnownPercentage()) {
        hash = (37 * hash) + KNOWN_PERCENTAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getKnownPercentage()));
      }
      if (hasFrequencyCount()) {
        hash = (37 * hash) + FREQUENCY_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFrequencyCount());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.ConcretenessRatingsProtos.Entry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.Entry)
        data.ConcretenessRatingsProtos.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.ConcretenessRatingsProtos.internal_static_data_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.ConcretenessRatingsProtos.internal_static_data_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.ConcretenessRatingsProtos.Entry.class, data.ConcretenessRatingsProtos.Entry.Builder.class);
      }

      // Construct using data.ConcretenessRatingsProtos.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bigram_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        rating_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        ratingSd_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        unknown_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        numPersons_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        knownPercentage_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        frequencyCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.ConcretenessRatingsProtos.internal_static_data_Entry_descriptor;
      }

      public data.ConcretenessRatingsProtos.Entry getDefaultInstanceForType() {
        return data.ConcretenessRatingsProtos.Entry.getDefaultInstance();
      }

      public data.ConcretenessRatingsProtos.Entry build() {
        data.ConcretenessRatingsProtos.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public data.ConcretenessRatingsProtos.Entry buildPartial() {
        data.ConcretenessRatingsProtos.Entry result = new data.ConcretenessRatingsProtos.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bigram_ = bigram_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rating_ = rating_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ratingSd_ = ratingSd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.unknown_ = unknown_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numPersons_ = numPersons_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.knownPercentage_ = knownPercentage_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.frequencyCount_ = frequencyCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.ConcretenessRatingsProtos.Entry) {
          return mergeFrom((data.ConcretenessRatingsProtos.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.ConcretenessRatingsProtos.Entry other) {
        if (other == data.ConcretenessRatingsProtos.Entry.getDefaultInstance()) return this;
        if (other.hasBigram()) {
          setBigram(other.getBigram());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        if (other.hasRatingSd()) {
          setRatingSd(other.getRatingSd());
        }
        if (other.hasUnknown()) {
          setUnknown(other.getUnknown());
        }
        if (other.hasNumPersons()) {
          setNumPersons(other.getNumPersons());
        }
        if (other.hasKnownPercentage()) {
          setKnownPercentage(other.getKnownPercentage());
        }
        if (other.hasFrequencyCount()) {
          setFrequencyCount(other.getFrequencyCount());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000080;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBigram()) {
          return false;
        }
        if (!hasRating()) {
          return false;
        }
        if (!hasRatingSd()) {
          return false;
        }
        if (!hasUnknown()) {
          return false;
        }
        if (!hasNumPersons()) {
          return false;
        }
        if (!hasKnownPercentage()) {
          return false;
        }
        if (!hasFrequencyCount()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.ConcretenessRatingsProtos.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.ConcretenessRatingsProtos.Entry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean bigram_ ;
      /**
       * <pre>
       * Whether it is a single word or a two-word expression.
       * </pre>
       *
       * <code>required bool bigram = 1;</code>
       */
      public boolean hasBigram() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Whether it is a single word or a two-word expression.
       * </pre>
       *
       * <code>required bool bigram = 1;</code>
       */
      public boolean getBigram() {
        return bigram_;
      }
      /**
       * <pre>
       * Whether it is a single word or a two-word expression.
       * </pre>
       *
       * <code>required bool bigram = 1;</code>
       */
      public Builder setBigram(boolean value) {
        bitField0_ |= 0x00000001;
        bigram_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether it is a single word or a two-word expression.
       * </pre>
       *
       * <code>required bool bigram = 1;</code>
       */
      public Builder clearBigram() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bigram_ = false;
        onChanged();
        return this;
      }

      private double rating_ ;
      /**
       * <pre>
       * The mean concreteness rating.
       * </pre>
       *
       * <code>required double rating = 2;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * The mean concreteness rating.
       * </pre>
       *
       * <code>required double rating = 2;</code>
       */
      public double getRating() {
        return rating_;
      }
      /**
       * <pre>
       * The mean concreteness rating.
       * </pre>
       *
       * <code>required double rating = 2;</code>
       */
      public Builder setRating(double value) {
        bitField0_ |= 0x00000002;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The mean concreteness rating.
       * </pre>
       *
       * <code>required double rating = 2;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rating_ = 0D;
        onChanged();
        return this;
      }

      private double ratingSd_ ;
      /**
       * <pre>
       * The standard deviation of the concreteness ratings.
       * </pre>
       *
       * <code>required double rating_sd = 3;</code>
       */
      public boolean hasRatingSd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * The standard deviation of the concreteness ratings.
       * </pre>
       *
       * <code>required double rating_sd = 3;</code>
       */
      public double getRatingSd() {
        return ratingSd_;
      }
      /**
       * <pre>
       * The standard deviation of the concreteness ratings.
       * </pre>
       *
       * <code>required double rating_sd = 3;</code>
       */
      public Builder setRatingSd(double value) {
        bitField0_ |= 0x00000004;
        ratingSd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The standard deviation of the concreteness ratings.
       * </pre>
       *
       * <code>required double rating_sd = 3;</code>
       */
      public Builder clearRatingSd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ratingSd_ = 0D;
        onChanged();
        return this;
      }

      private int unknown_ ;
      /**
       * <pre>
       * The number of persons indicating they did not know the word.
       * </pre>
       *
       * <code>required uint32 unknown = 4;</code>
       */
      public boolean hasUnknown() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * The number of persons indicating they did not know the word.
       * </pre>
       *
       * <code>required uint32 unknown = 4;</code>
       */
      public int getUnknown() {
        return unknown_;
      }
      /**
       * <pre>
       * The number of persons indicating they did not know the word.
       * </pre>
       *
       * <code>required uint32 unknown = 4;</code>
       */
      public Builder setUnknown(int value) {
        bitField0_ |= 0x00000008;
        unknown_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The number of persons indicating they did not know the word.
       * </pre>
       *
       * <code>required uint32 unknown = 4;</code>
       */
      public Builder clearUnknown() {
        bitField0_ = (bitField0_ & ~0x00000008);
        unknown_ = 0;
        onChanged();
        return this;
      }

      private int numPersons_ ;
      /**
       * <pre>
       * The total number of persons who rated the word.
       * </pre>
       *
       * <code>required uint32 num_persons = 5;</code>
       */
      public boolean hasNumPersons() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * The total number of persons who rated the word.
       * </pre>
       *
       * <code>required uint32 num_persons = 5;</code>
       */
      public int getNumPersons() {
        return numPersons_;
      }
      /**
       * <pre>
       * The total number of persons who rated the word.
       * </pre>
       *
       * <code>required uint32 num_persons = 5;</code>
       */
      public Builder setNumPersons(int value) {
        bitField0_ |= 0x00000010;
        numPersons_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The total number of persons who rated the word.
       * </pre>
       *
       * <code>required uint32 num_persons = 5;</code>
       */
      public Builder clearNumPersons() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numPersons_ = 0;
        onChanged();
        return this;
      }

      private double knownPercentage_ ;
      /**
       * <pre>
       * Percentage participants who knew the word.
       * </pre>
       *
       * <code>required double known_percentage = 6;</code>
       */
      public boolean hasKnownPercentage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * Percentage participants who knew the word.
       * </pre>
       *
       * <code>required double known_percentage = 6;</code>
       */
      public double getKnownPercentage() {
        return knownPercentage_;
      }
      /**
       * <pre>
       * Percentage participants who knew the word.
       * </pre>
       *
       * <code>required double known_percentage = 6;</code>
       */
      public Builder setKnownPercentage(double value) {
        bitField0_ |= 0x00000020;
        knownPercentage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Percentage participants who knew the word.
       * </pre>
       *
       * <code>required double known_percentage = 6;</code>
       */
      public Builder clearKnownPercentage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        knownPercentage_ = 0D;
        onChanged();
        return this;
      }

      private long frequencyCount_ ;
      /**
       * <pre>
       * The SUBTLEX-US frequency count (on a total of 51 million).
       * </pre>
       *
       * <code>required uint64 frequency_count = 7;</code>
       */
      public boolean hasFrequencyCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * The SUBTLEX-US frequency count (on a total of 51 million).
       * </pre>
       *
       * <code>required uint64 frequency_count = 7;</code>
       */
      public long getFrequencyCount() {
        return frequencyCount_;
      }
      /**
       * <pre>
       * The SUBTLEX-US frequency count (on a total of 51 million).
       * </pre>
       *
       * <code>required uint64 frequency_count = 7;</code>
       */
      public Builder setFrequencyCount(long value) {
        bitField0_ |= 0x00000040;
        frequencyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The SUBTLEX-US frequency count (on a total of 51 million).
       * </pre>
       *
       * <code>required uint64 frequency_count = 7;</code>
       */
      public Builder clearFrequencyCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        frequencyCount_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Adjective, Noun, Verb, N/A.
       * </pre>
       *
       * <code>required string type = 8;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.Entry)
    }

    // @@protoc_insertion_point(class_scope:data.Entry)
    private static final data.ConcretenessRatingsProtos.Entry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.ConcretenessRatingsProtos.Entry();
    }

    public static data.ConcretenessRatingsProtos.Entry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Entry>
        PARSER = new com.google.protobuf.AbstractParser<Entry>() {
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Entry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    public data.ConcretenessRatingsProtos.Entry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RatingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.Ratings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */
    int getRatingsMapCount();
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */
    boolean containsRatingsMap(
        java.lang.String key);
    /**
     * Use {@link #getRatingsMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry>
    getRatingsMap();
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */
    java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry>
    getRatingsMapMap();
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    data.ConcretenessRatingsProtos.Entry getRatingsMapOrDefault(
        java.lang.String key,
        data.ConcretenessRatingsProtos.Entry defaultValue);
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    data.ConcretenessRatingsProtos.Entry getRatingsMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code data.Ratings}
   */
  public  static final class Ratings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.Ratings)
      RatingsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ratings.newBuilder() to construct.
    private Ratings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ratings() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ratings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ratingsMap_ = com.google.protobuf.MapField.newMapField(
                    RatingsMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, data.ConcretenessRatingsProtos.Entry>
              ratingsMap__ = input.readMessage(
                  RatingsMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              ratingsMap_.getMutableMap().put(
                  ratingsMap__.getKey(), ratingsMap__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.ConcretenessRatingsProtos.internal_static_data_Ratings_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetRatingsMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.ConcretenessRatingsProtos.internal_static_data_Ratings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.ConcretenessRatingsProtos.Ratings.class, data.ConcretenessRatingsProtos.Ratings.Builder.class);
    }

    public static final int RATINGS_MAP_FIELD_NUMBER = 1;
    private static final class RatingsMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, data.ConcretenessRatingsProtos.Entry> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, data.ConcretenessRatingsProtos.Entry>newDefaultInstance(
                  data.ConcretenessRatingsProtos.internal_static_data_Ratings_RatingsMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  data.ConcretenessRatingsProtos.Entry.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, data.ConcretenessRatingsProtos.Entry> ratingsMap_;
    private com.google.protobuf.MapField<java.lang.String, data.ConcretenessRatingsProtos.Entry>
    internalGetRatingsMap() {
      if (ratingsMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RatingsMapDefaultEntryHolder.defaultEntry);
      }
      return ratingsMap_;
    }

    public int getRatingsMapCount() {
      return internalGetRatingsMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    public boolean containsRatingsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRatingsMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRatingsMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> getRatingsMap() {
      return getRatingsMapMap();
    }
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    public java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> getRatingsMapMap() {
      return internalGetRatingsMap().getMap();
    }
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    public data.ConcretenessRatingsProtos.Entry getRatingsMapOrDefault(
        java.lang.String key,
        data.ConcretenessRatingsProtos.Entry defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> map =
          internalGetRatingsMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
     */

    public data.ConcretenessRatingsProtos.Entry getRatingsMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> map =
          internalGetRatingsMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (data.ConcretenessRatingsProtos.Entry item : getRatingsMapMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetRatingsMap(),
          RatingsMapDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, data.ConcretenessRatingsProtos.Entry> entry
           : internalGetRatingsMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, data.ConcretenessRatingsProtos.Entry>
        ratingsMap__ = RatingsMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, ratingsMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.ConcretenessRatingsProtos.Ratings)) {
        return super.equals(obj);
      }
      data.ConcretenessRatingsProtos.Ratings other = (data.ConcretenessRatingsProtos.Ratings) obj;

      boolean result = true;
      result = result && internalGetRatingsMap().equals(
          other.internalGetRatingsMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetRatingsMap().getMap().isEmpty()) {
        hash = (37 * hash) + RATINGS_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRatingsMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.ConcretenessRatingsProtos.Ratings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.ConcretenessRatingsProtos.Ratings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.Ratings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.Ratings)
        data.ConcretenessRatingsProtos.RatingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.ConcretenessRatingsProtos.internal_static_data_Ratings_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetRatingsMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableRatingsMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.ConcretenessRatingsProtos.internal_static_data_Ratings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.ConcretenessRatingsProtos.Ratings.class, data.ConcretenessRatingsProtos.Ratings.Builder.class);
      }

      // Construct using data.ConcretenessRatingsProtos.Ratings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableRatingsMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.ConcretenessRatingsProtos.internal_static_data_Ratings_descriptor;
      }

      public data.ConcretenessRatingsProtos.Ratings getDefaultInstanceForType() {
        return data.ConcretenessRatingsProtos.Ratings.getDefaultInstance();
      }

      public data.ConcretenessRatingsProtos.Ratings build() {
        data.ConcretenessRatingsProtos.Ratings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public data.ConcretenessRatingsProtos.Ratings buildPartial() {
        data.ConcretenessRatingsProtos.Ratings result = new data.ConcretenessRatingsProtos.Ratings(this);
        int from_bitField0_ = bitField0_;
        result.ratingsMap_ = internalGetRatingsMap();
        result.ratingsMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.ConcretenessRatingsProtos.Ratings) {
          return mergeFrom((data.ConcretenessRatingsProtos.Ratings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.ConcretenessRatingsProtos.Ratings other) {
        if (other == data.ConcretenessRatingsProtos.Ratings.getDefaultInstance()) return this;
        internalGetMutableRatingsMap().mergeFrom(
            other.internalGetRatingsMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (data.ConcretenessRatingsProtos.Entry item : getRatingsMapMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.ConcretenessRatingsProtos.Ratings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.ConcretenessRatingsProtos.Ratings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, data.ConcretenessRatingsProtos.Entry> ratingsMap_;
      private com.google.protobuf.MapField<java.lang.String, data.ConcretenessRatingsProtos.Entry>
      internalGetRatingsMap() {
        if (ratingsMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RatingsMapDefaultEntryHolder.defaultEntry);
        }
        return ratingsMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, data.ConcretenessRatingsProtos.Entry>
      internalGetMutableRatingsMap() {
        onChanged();;
        if (ratingsMap_ == null) {
          ratingsMap_ = com.google.protobuf.MapField.newMapField(
              RatingsMapDefaultEntryHolder.defaultEntry);
        }
        if (!ratingsMap_.isMutable()) {
          ratingsMap_ = ratingsMap_.copy();
        }
        return ratingsMap_;
      }

      public int getRatingsMapCount() {
        return internalGetRatingsMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public boolean containsRatingsMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetRatingsMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRatingsMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> getRatingsMap() {
        return getRatingsMapMap();
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> getRatingsMapMap() {
        return internalGetRatingsMap().getMap();
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public data.ConcretenessRatingsProtos.Entry getRatingsMapOrDefault(
          java.lang.String key,
          data.ConcretenessRatingsProtos.Entry defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> map =
            internalGetRatingsMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public data.ConcretenessRatingsProtos.Entry getRatingsMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> map =
            internalGetRatingsMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearRatingsMap() {
        internalGetMutableRatingsMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public Builder removeRatingsMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRatingsMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry>
      getMutableRatingsMap() {
        return internalGetMutableRatingsMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */
      public Builder putRatingsMap(
          java.lang.String key,
          data.ConcretenessRatingsProtos.Entry value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRatingsMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .data.Entry&gt; ratings_map = 1;</code>
       */

      public Builder putAllRatingsMap(
          java.util.Map<java.lang.String, data.ConcretenessRatingsProtos.Entry> values) {
        internalGetMutableRatingsMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.Ratings)
    }

    // @@protoc_insertion_point(class_scope:data.Ratings)
    private static final data.ConcretenessRatingsProtos.Ratings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.ConcretenessRatingsProtos.Ratings();
    }

    public static data.ConcretenessRatingsProtos.Ratings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Ratings>
        PARSER = new com.google.protobuf.AbstractParser<Ratings>() {
      public Ratings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ratings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ratings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ratings> getParserForType() {
      return PARSER;
    }

    public data.ConcretenessRatingsProtos.Ratings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Entry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Ratings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Ratings_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Ratings_RatingsMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Ratings_RatingsMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031concretness_ratings.proto\022\004data\"\241\001\n\005En" +
      "try\022\016\n\006bigram\030\001 \002(\010\022\016\n\006rating\030\002 \002(\001\022\021\n\tr" +
      "ating_sd\030\003 \002(\001\022\017\n\007unknown\030\004 \002(\r\022\023\n\013num_p" +
      "ersons\030\005 \002(\r\022\030\n\020known_percentage\030\006 \002(\001\022\027" +
      "\n\017frequency_count\030\007 \002(\004\022\014\n\004type\030\010 \002(\t\"}\n" +
      "\007Ratings\0222\n\013ratings_map\030\001 \003(\0132\035.data.Rat" +
      "ings.RatingsMapEntry\032>\n\017RatingsMapEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\032\n\005value\030\002 \001(\0132\013.data.Entry" +
      ":\0028\001B!\n\004dataB\031ConcretenessRatingsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Entry_descriptor,
        new java.lang.String[] { "Bigram", "Rating", "RatingSd", "Unknown", "NumPersons", "KnownPercentage", "FrequencyCount", "Type", });
    internal_static_data_Ratings_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_Ratings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Ratings_descriptor,
        new java.lang.String[] { "RatingsMap", });
    internal_static_data_Ratings_RatingsMapEntry_descriptor =
      internal_static_data_Ratings_descriptor.getNestedTypes().get(0);
    internal_static_data_Ratings_RatingsMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Ratings_RatingsMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
