# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import answer_service_pb2 as answer__service__pb2


class AnswerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Answer = channel.unary_unary(
        '/services.AnswerService/Answer',
        request_serializer=answer__service__pb2.AnswerRequest.SerializeToString,
        response_deserializer=answer__service__pb2.AnswerResponse.FromString,
        )


class AnswerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Answer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnswerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Answer': grpc.unary_unary_rpc_method_handler(
          servicer.Answer,
          request_deserializer=answer__service__pb2.AnswerRequest.FromString,
          response_serializer=answer__service__pb2.AnswerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'services.AnswerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
