# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: answer_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='answer_service.proto',
  package='services',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x61nswer_service.proto\x12\x08services\".\n\rAnswerRequest\x12\x1d\n\x15json_question_dataset\x18\x01 \x02(\t\"3\n\x0e\x41nswerResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x01\x12\x11\n\texit_code\x18\x02 \x02(\t2N\n\rAnswerService\x12=\n\x06\x41nswer\x12\x17.services.AnswerRequest\x1a\x18.services.AnswerResponse\"\x00\x42\x1e\n\x07\x63lientsB\x13\x41nswerServiceProtos')
)




_ANSWERREQUEST = _descriptor.Descriptor(
  name='AnswerRequest',
  full_name='services.AnswerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_question_dataset', full_name='services.AnswerRequest.json_question_dataset', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=80,
)


_ANSWERRESPONSE = _descriptor.Descriptor(
  name='AnswerResponse',
  full_name='services.AnswerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='services.AnswerResponse.scores', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='services.AnswerResponse.exit_code', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['AnswerRequest'] = _ANSWERREQUEST
DESCRIPTOR.message_types_by_name['AnswerResponse'] = _ANSWERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnswerRequest = _reflection.GeneratedProtocolMessageType('AnswerRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERREQUEST,
  __module__ = 'answer_service_pb2'
  # @@protoc_insertion_point(class_scope:services.AnswerRequest)
  ))
_sym_db.RegisterMessage(AnswerRequest)

AnswerResponse = _reflection.GeneratedProtocolMessageType('AnswerResponse', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERRESPONSE,
  __module__ = 'answer_service_pb2'
  # @@protoc_insertion_point(class_scope:services.AnswerResponse)
  ))
_sym_db.RegisterMessage(AnswerResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007clientsB\023AnswerServiceProtos'))

_ANSWERSERVICE = _descriptor.ServiceDescriptor(
  name='AnswerService',
  full_name='services.AnswerService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=135,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='Answer',
    full_name='services.AnswerService.Answer',
    index=0,
    containing_service=None,
    input_type=_ANSWERREQUEST,
    output_type=_ANSWERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANSWERSERVICE)

DESCRIPTOR.services_by_name['AnswerService'] = _ANSWERSERVICE

# @@protoc_insertion_point(module_scope)
